### ISSUE TITLE
如何调试debug工程

### ISSUE THREAD

**Issue by DexSinis** [ichenkaihua/ssm-easy-template#1]
真抱歉，现在春节放假在家，家里没有网络，所以没有回复。
关于调试问题，推荐使用idea 付费版，使用自带的jee(tomcat)插件后，可以调试，这种方式调试更简单。
还有一直，就是结合jetty和gradle以及idea社区版 https://github.com/akhikhl/gretty/issues/36
http://akhikhl.github.io/gretty-doc/Debugger-support.html

**Comment by DexSinis** [comment]
解决了

**Comment by DexSinis** [comment]
还有一个问题，我怎么用debu的模式启动jetty呢，程序现在调试不了，希望修改一下能提供例如  ./gradlew  appStart  debug这样的命令方便调试，或者有方法的话告诉一下我....谢谢

**Comment by ichenkaihua** [comment]
真抱歉，现在春节放假在家，家里没有网络，所以没有回复。
关于调试问题，推荐使用idea 付费版，使用自带的jee(tomcat)插件后，可以调试，这种方式调试更简单。
还有一直，就是结合jetty和gradle以及idea社区版 akhikhl/gretty#36
http://akhikhl.github.io/gretty-doc/Debugger-support.html

**Comment by ichenkaihua** [comment]
@DexSinis 
真抱歉，现在春节放假在家，家里没有网络，所以没有回复。
关于调试问题，推荐使用idea 付费版，使用自带的jee(tomcat)插件后，可以调试，这种方式调试更简单。
还有一直，就是结合jetty和gradle以及idea社区版 akhikhl/gretty#36
可以参考这篇博客
http://www.chenkaihua.com/2016/02/20/idea-webapp-remote--debug-via-gretty/
