### ISSUE TITLE
修改库表引起的migrate失败的checksum问题

### ISSUE THREAD

**Issue by sirs05** [ichenkaihua/ssm-easy-template#2]
看stackflow上的指导是要用gradle flyway:repair来解决，在这个集成方案下应该怎么处理？

**Comment by sirs05** [comment]
已解决  
执行 ./gradlew flywayRepair

**Comment by sirs05** [comment]
然后似乎并没有解决涉及的字段没有更新的问题。。请求指导。。
重新执行了
0,gradlew flywayRepair
1,gradlew flywayMigrate
2,gradlew build

提示：Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'USER_iD' in 'field list'
这个user_id 已经被都替换成为userId了

**Comment by sirs05** [comment]
感觉是mapper的脚本为 user表的主键id自动生成了 user_id 这个键名，但是目前没有在配置中找到在哪里修改

**Comment by ichenkaihua** [comment]
@sirs05  
- 建议你直接在`db/migration` 下新建数据库迁移的sql文件,在sql文件里写数据库改动语句,这样能避免迁移冲突.
- 如果修改了表结构,则执行一次`gradle mybatisGenerate` ,这个task作用是生成mapper和entity
- 如果修改幅度不大,或者不想重新生成mapper和entity.也可以自己手动改
  1. 在`src/main/java/com/github/ichenkaihua/model/User.java`,在修改的字段`private string id`加上注解`@column(name="user_id")`,
  2. 修改`src/main/resources/mybatis_mapper/UserMapper.xml`,将`<id column="id" jdbcType="INTEGER" property="id" />`修改为`<id column="id" jdbcType="INTEGER" property="user_id" />`

**Comment by sirs05** [comment]
跟mapper的作者确认了，问题是出在我使用userId作为model里面的字段名字，而他在转化成对应的sql语句时，有驼峰转下划线的命名规则。所以出现了不一致。

**Comment by sirs05** [comment]
我之前使用的userI(大写I)d 字段名

**Comment by ichenkaihua** [comment]
@sirs05 
详细使用方法，请参考：https://github.com/abel533/Mapper
