### ISSUE TITLE
MacOS idea 2016使用idea导入，tomcat 7 运行，打开主页报错

### ISSUE THREAD

**Issue by yy307** [ichenkaihua/ssm-easy-template#6]
MacOS idea 2016使用idea导入，tomcat 7 运行，打开主页报错

“
HTTP Status 500 - Filter execution threw an exception

type Exception report

message Filter execution threw an exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Filter execution threw an exception
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
root cause

java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getStatus()I
	com.github.ichenkaihua.filter.RequestLogFilter.doFilter(RequestLogFilter.java:62)
	com.github.ichenkaihua.filter.AbstractFilter.doFilter(AbstractFilter.java:33)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
note The full stack trace of the root cause is available in the Apache Tomcat/6.0.41 logs.
”

**Comment by ichenkaihua** [comment]
@yy307  目测是没有'javax.servlet:javax.servlet-api:3.1.0`这个依赖，你确定gradle build完了么

**Comment by thecoding** [comment]
build的时候报错： Could not set unknown property 'port' for object of type org.akhikhl.gretty.GrettyExtension.  用的是idea，jar包都加载出来了

**Comment by thecoding** [comment]
解决了。将port改成httpPort就好了

**Comment by ichenkaihua** [comment]
@thecoding 谢谢你的反馈，请问你有更新gretty版本么

**Comment by thecoding** [comment]
@ichenkaihua gradle用的是3.2的 你项目中用的是2.3 应该是我这个版本比较高
